set_property SRC_FILE_INFO {cfile:C:/Users/Nicola/Documents/university/MSc_physics_of_data/S1_management_and_analysis_of_physics_dataset/lab_projects/03_multiplexer41/multiplexer.srcs/constrs_1/new/mapping.xdc rfile:../../../multiplexer.srcs/constrs_1/new/mapping.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN D9      IOSTANDARD LVCMOS33 } [get_ports { a_in }]; #I0_L6N_T0_VREF_16 Sch=btn[0]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN C9      IOSTANDARD LVCMOS33 } [get_ports { b_in }]; #I0_L11P_T1_SRCC_16 Sch=btn[1]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN B9     IOSTANDARD LVCMOS33 } [get_ports { c_in }]; #I0_L11N_T1_SRCC_16 Sch=btn[2]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN B8     IOSTANDARD LVCMOS33 } [get_ports { d_in }]; #I0_L12P_T1_MRCC_16 Sch=btn[3]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN A8      IOSTANDARD LVCMOS33 } [get_ports { sel_in[0] }]; #I0_L12N_T1_MRCC_16 Sch=sw[0]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN C11     IOSTANDARD LVCMOS33 } [get_ports { sel_in[1] }]; #I0_L13P_T2_MRCC_16 Sch=sw[1]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN E1      IOSTANDARD LVCMOS33 } [get_ports { y_out }]; #I0_L18_T2_35 Sch=led0_b
